# Generated by Django 4.2.6 on 2023-10-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uploader", "0001_initial"),
        ("garagem", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="veiculo",
            name="capa",
            field=models.ManyToManyField(related_name="+", to="uploader.image"),
        ),
    ]
